[package]
name = "rubigo-cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rubigo-build = { path = "../rubigo-build" }
cmd_lib = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
